# Generated by Django 4.1.1 on 2022-10-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
